[AGENT-4318] Implement UploadDatasetOperator
datarobot/airflow-provider-datarobot pull request #10
Opened 2023-04-11 16:38 UTC by oleksandr-saienko

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Added new Airflow Operator for Uploading local file to DataRobot AI Catalog
Bump version to 0.0.5
## Rationale
Uploading local file to DataRobot AI Catalog is important missing part in out Airflow Provider

2023-04-11 17:40 UTC, andrius-senulis requested changes
Since we don't have automation in the repo yet, can you please manually run lint, black, isort, typecheck, check-licenses ([defined in Makefile](https://github.com/datarobot/airflow-provider-datarobot/blob/main/Makefile))?

2023-04-11 17:40 UTC, andrius-senulis commented on datarobot_provider/operators/ai_catalog.py
> +            **kwargs: Any,
overindented

2023-04-12 08:19 UTC, andrius-senulis commented on README.md
> +- `UploadDatasetOperator`
I would place it as the first operator in the list, as it would fit the logical flow of actions in DR pipeline.

2023-04-12 08:19 UTC, andrius-senulis approved these changes
One minor comment, otherwise LGTM.

2023-04-12 14:59 UTC, elatt requested changes
Let's get the Jenkins infra (#11) merged in first.

2023-04-17 11:18 UTC, elatt commented
Jenkins run

2023-04-17 11:19 UTC, elatt approved these changes

2023-04-17 13:04 UTC, merged