[AGENT-5360] Create Airflow Operator for Custom Job
datarobot/airflow-provider-datarobot pull request #86
Opened 2024-02-19 15:51 UTC by oleksandr-saienko

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Added the next operatos:
 - CreateCustomJobOperator
 - AddFilesToCustomJobOperator
 - SetCustomJobExecutionEnvironmentOperator
 - SetCustomJobRuntimeParametersOperator
 - RunCustomJobOperator
 - ListExecutionEnvironmentOperator
 - ListExecutionEnvironmentVersionsOperator

## Rationale

2024-02-19 15:51 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 16:04 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 16:17 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 17:12 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 17:13 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 17:17 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 17:19 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-19 17:21 UTC, datarobot-devinfragit6 commented
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

2024-02-20 09:03 UTC, alexromanyuk approved these changes

2024-02-21 15:45 UTC, brianbelljr commented
FYI this is coming to experimental client - https://github.com/datarobot/public_api_client/pull/2941

2024-02-21 15:48 UTC, brianbelljr commented on datarobot_provider/example_dags/datarobot_custom_job_dag.py
> +    create_custom_job_op = CreateCustomJobOperator(
Does it make sense to create another kind of create operator which includes files, environment and runtime parameters all in one? This way the DAG could be simplified. Having these more specific operators makes sense, but I think a super-creator operator could be useful.

2024-02-21 18:08 UTC, dulcardo approved these changes

2024-02-22 21:43 UTC, elatt requested changes
I recommend shelving this PR until the Python client has native support for Custom Jobs.

2024-02-22 21:43 UTC, elatt commented on datarobot_provider/operators/custom_job.py
> +        )
With Custom Jobs going GA in 10.0 and having support in the Python Client at that time, I think we should postpone this PR until that time.

2025-02-20 19:29 UTC, mjnitz02 commented
Closing this PR as its very stale/expired

2025-02-20 19:29 UTC, closed without merging